### ISSUE TITLE
Licence and Contributions

### ISSUE THREAD

**Issue by AsherGlick** [j3nda/speed-dial-chrome#1]
I cant seem to find a licence file for this project. I would like to help out with this project and a licence file would be very helpful to contributors.

**Comment by j3nda** [comment]
i will ask original author for this (he is only on g+ and this repository was created with his agree), please be tuned and wait.

**Comment by waffleau** [comment]
License will be BSD. I'll add a license file shortly.

**Comment by j3nda** [comment]
okay. try it. i added your accont as collaborator.
