### ISSUE TITLE
Vertical centering bug

### ISSUE THREAD

**Issue by User99gmxat** [j3nda/speed-dial-chrome#13]
Use latest version and Iron 32 - a Chrome 32 derivate and have the vertical centering bug. 

![vertical centering bug](https://f.cloud.github.com/assets/5928155/2075557/786906ca-8d8f-11e3-8cec-375d02698022.png)

**Comment by heavensrevenge** [comment]
Question: Where is the bug? The entries look vertically centered to me (equal space on the top and bottom of the entries). Is there some odd behaviour that isn't visible in that screenshot?

**Comment by AsherGlick** [comment]
It may have been unclear that vertical centering was a feature. Is there a setting box to turn vertical centering on / off? I am not in front of a machine with speed dial installed or I would check myself.

**Comment by User99gmxat** [comment]
I like that this is shown in that way:

![786906ca-8d8f-11e3-8cec-375d02698022](https://f.cloud.github.com/assets/5928155/2077595/bb4ce7a8-8db3-11e3-96e4-6ab7740a827e.png)

In Release Notes you wrote: " 2.4.3: Resolved vertical centering bug "
So I thought this is a bug and the bookmarks should NOT be centered. OK, it this is a new feature than could there be an option to get that not centered? ;)

**Comment by heavensrevenge** [comment]
Heh no it was a different bug, actually I didn't code in an option to turn vertical centering on/off, I actually considered it to be a bug that vertical centering wasn't there to begin with :P 
But yes I could make an option for vertical centering since I can update jQuery to the 2.1 final version while I'm at it.

**Comment by User99gmxat** [comment]
That would be great to have an option. Thx

**Comment by User99gmxat** [comment]
Thx for the new version! All is working fine now
