### ISSUE TITLE
Show Configuration Gear & Solution

### ISSUE THREAD

**Issue by RedBaron2** [j3nda/speed-dial-chrome#7]
I do not like having the Configuration Gear always in my face on that tab. I could have just added a css to hide the options <div>, but that would have only been for me. This is more a contribution than a personal edit.

I changed these files common.js, newtab.js, options.js, and options.html with my edited lines of code.

common.js edit edit by finding this line of code

defaultStorage("show_folder_list", "true");

then add these lines above it

// RB start common.js edit to show or not the options gear
defaultStorage("options", "true");
// RB finis common.js edit to show or not the options gear

newtab.js edit edit by finding this line of code

loadSetting($("#folder_list"), localStorage["show_folder_list"]);

then add these lines above it

// RB start newtab.js edit to show or not the options gear
loadSetting($("#options"), localStorage["options"]);
// RB finis newtab.js edit to show or not the options gear

options.js edit by finding this line of code

$("#show_folder_list").prop("checked", (localStorage["show_folder_list"] === "true"));

then add these lines above it

// RB start options.js edit to show or not the options gear
$("#options").prop("checked", (localStorage["options"] === "true"));
// RB finis options.js edit to show or not the options gear

options.html edit by finding these lines of code

<tr>
<td class="field"><label for="show_new_entry">Show [+] button</label></td>
<td class="value"><input type="checkbox" id="show_new_entry" value="true" /></td>
</tr>

then add these lines above it

<tr>
<td class="field"><label for="options">Show Configuration Gear</label></td>
<td class="value"><input type="checkbox" id="options" value="true" /></td>
</tr>

This is off by Default, and can be used freely long as credit is given and my comment lines are kept in tact. The options gear could also be adjusted for size, but I didn't feel like messing with the code that much. I hope everyone can make us of the updates if they would like to manually edit the files.
## Keep up the great extension. Opera based on presto will be missed.

RB

**Comment by heavensrevenge** [comment]
You can close this @waffleau :)

**Comment by heavensrevenge** [comment]
You can close this issue @waffleau
